version: '3.4'

services:
  dockerproject:
    container_name: docker-project-container
    image: ${DOCKER_REGISTRY-}dockerproject
    build:
      context: .
      dockerfile: DockerProject/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  #sql server service
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver_data:/var/opt/mssql  # Bind mount local directory to container directory
    networks:
      - sqlnet

networks:
  sqlnet: